import { NaturalNoteNames, Note } from './types';
export declare const NAMESPACE = "SoLa";
export declare const STAFF_LINES_COUNT = 5;
export declare const STAFF_LINE_HEIGHT = 8;
export declare const STAFF_LINE_WIDTH = 1;
export declare const TOTAL_HEIGHT_STAFF_LINES: number;
export declare const GRAND_STAFF_SPACING = 40;
export declare const LEDGER_LINE_LENGTH = 2;
export declare const NOTE_START_X = 34;
export declare const NOTE_SPACING = 24;
export declare const TOP_STAFF_LINE_INDEX = 0;
export declare const BOTTOM_STAFF_LINE_INDEX = 8;
export declare const GLOBAL_GLYPH_SCALE = 0.2;
export type ClefTypes = "treble" | "bass" | "grand";
export type ClefStaffParams = {
    clefHeightPadding: number;
    groupYOffset: number;
    clefNoteReference: Note;
};
export declare const CLEF_STAFF_PARAMS: Partial<Record<ClefTypes, ClefStaffParams>>;
export declare const NATURAL_NOTE_NAMES_ARR: NaturalNoteNames[];
